name: FastAPI Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Prevents hanging jobs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'  # Enable dependency caching

      - name: Install dependencies
        working-directory: ./testing-automation 
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest requests pytest-cov
          
      - name: Verify installed packages
        run: pip list

      - name: Start FastAPI server
        run: |
          uvicorn apiserver:app --host 0.0.0.0 --port 8000 &
          echo $! > server.pid  # Save PID for later cleanup
        env:
          PYTHONUNBUFFERED: 1

      - name: Wait for server startup
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          maxAttempts: 10
          secondsBetweenAttempts: 3
          checkName: 'server-healthcheck'
          command: |
            curl -s http://localhost:8000/health | grep -q "OK"

      - name: Run tests with coverage
        run: |
          pytest test-automation/testAutomationPytest.py -v --cov=.
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3

      - name: Stop server (cleanup)
        if: always()  # Ensures cleanup even if tests fail
        run: |
          kill $(cat server.pid) || true
